apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: order-processing
  labels:
    app: payment-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: order-processing/payment-service:latest
        ports:
        - containerPort: 50053
          name: grpc
        - containerPort: 8082
          name: metrics
        env:
        - name: PORT
          value: "50053"
        - name: METRICS_PORT
          value: "8082"
        - name: JAEGER_ENDPOINT
          value: "http://jaeger:14268/api/traces"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: order-processing
  labels:
    app: payment-service
spec:
  selector:
    app: payment-service
  ports:
  - name: grpc
    port: 50053
    targetPort: 50053
  - name: metrics
    port: 8082
    targetPort: 8082
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: payment-service-hpa
  namespace: order-processing
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: payment-service
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80

